
name: Code Quality Checker
on:
  pull_request:
    branches: [ "main" ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: code grab
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: setup Python
      - name: Set up python 3.X
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Step 3: libraries
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r api/requirements.txt
          pip install -r monitoring/requirements.txt

      # Step 4: linter.. I hate linters
      - name: Lint with flake8
        run: flake8 .

      # Step 5: tests 
      - name: Test with pytest
        run: pytest